apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aks-app
      version: latest
  template:
    metadata:
      labels:
        app: aks-app
        version: latest
    spec:
      containers:
      - name: aks-app
        image: {ACRname}.azurecr.io/aksapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: aks-app
  labels: 
    app: aks-app
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: aks-app
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: aks-app
spec:
  hosts:
  - "*"
  gateways:
  - aks-app-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: aks-app.aksapp.svc.cluster.local
        subset: {old_version}
        port:
          number: 80
      weight: 80
    - destination:
        host: aks-app.aksapp.svc.cluster.local
        subset: latest
        port:
          number: 80
      weight: 20
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: aks-app-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: aksapp-destination
spec:
  host: aks-app.aksapp.svc.cluster.local
  subsets:
  - name: {old_version}
    labels:
      version: {old_version}
  - name: latest
    labels:
      version: latest
